### ISSUE TITLE
About Selectricks

### ISSUE THREAD

**Issue by Yousefv1** [unanimated/luaegisub#12]
hi..
I Try to select multiple lines non-contiguous by line NUM such as: 4, 35, 78, 120... in one time
But it didn't work!
I don't know whether the problem is from the script or the entered formula

is there a way to select multiple lines non-contiguous by line NUM in one click?

**Comment by unanimated** [comment]
Nope. Why would you even do that? Isn't it easier to just ctrl+click the lines than to type their numbers?

**Comment by Yousefv1** [comment]
Because I often check the shiftcut.lue changes, some time on 30 Lines Total, and i Record only the line numbers I want in notepad, may 7 or 15 Lines mostly, than i Apply shiftcut.lue on it only.
This is hard when doing this like this Select the lines manually About Three Times! 
that why I ask about this feature..

**Comment by unanimated** [comment]
I see. If I understand it right, you run ShiftCut and go through ~30 lines that were changed and note down ones you want to keep the changes for. The you undo ShiftCut and run it again on the lines you want. That's a bit tricky.
One way to do it would be to mark the lines you want with * in Effect, but because of the undo you'd have to copy the Effect field of the whole script with MultiCopy, then undo everything and paste the Effect back, and then select lines with * in Effect. Still kinda long, but probably better than Notepad.
To be honest, I would just retime the lines where I don't like the ShiftCut changes, since you're already going through them one by one.
The most efficient solution would be to set up ShiftCut with values that do what you want.
I'm not really sure why you're dissatisfied with half the changes, but tweaking the settings should help, and retiming the few lines you don't like would seem more efficient than what you're currently doing. That's my take based on what you said.

**Comment by Yousefv1** [comment]
Thank you very much, I read and benefited from it
