### ISSUE TITLE
Hi, how are you? How to use the ua.EncodeHardsub.lua ?  I'm noob, thanks ! Wait you online

### ISSUE THREAD

**Issue by Aegisub2019** [unanimated/luaegisub#8]
Hi, how to use the ua.EncodeHardsub.lua ?  I'm noob, thanks !
I try more times and it not work, i use it has errors.
Can you make a video tutorial at Youtube?
I use the Aegisub 3.2.2 .
Thanks you so muck !

![r](https://user-images.githubusercontent.com/55534428/65232531-2d2e6980-da86-11e9-819e-e644615aecdb.jpg)

![新建位图图像](https://user-images.githubusercontent.com/55534428/65232255-b2654e80-da85-11e9-86ee-6050fd66bba0.jpg)

**Comment by unanimated** [comment]
As for the script, everything necessary should be in the manual.
http://unanimated.hostfree.pw/ts/scripts-manuals.htm#enchsub

But what I'm seeing in your cmd.exe is an error from x264.exe. It seems like your version of x264.exe doesn't support mp4 output. Try to get a different version: http://x264.nl/x264_main.php
(Looks like only the "mirror 06" links work.)

**Comment by Aegisub2019** [comment]
hi guy, I has download the x264.exe in the link you give me ! it doesn't work and error!
(http://x264.nl/x264_main.php) it seem that is a old version.
and i study the tutorial from you link before, i have try it many times.
but cann't work.
So i contacted you.

**Comment by Aegisub2019** [comment]
![rt](https://user-images.githubusercontent.com/55534428/65261904-1277e700-dabe-11e9-8516-2e858a1a6351.png)

**Comment by Aegisub2019** [comment]
Hi guy, i found a bug in your script, it cann't select the Target folder ! 
When i try to select the custom, it open a file select window.

**Comment by unanimated** [comment]
1. I just tried encoding a hardsubbed mp4 video with the 32bit 8bit-depth x264 from the link I gave you. It worked fine. So the script works, and your settings look OK. The problem is not with the script.

2. I really don't know why x264.exe is giving you that error. Like I said, I tested the x264 file from the website and encoded a hardsubbed clip just fine. If you put the file in the place you have selected in the script and it still doesn't work, then I don't know what the problem is. I'm not an expert on video encoding. You'd have to ask somebody who understands encoding and x264.

3. "it cann't select the Target folder"
When you open that dialog, it says "Target folder for encodes (Select any file in it)", so that's what you should do. I think the Aegisub options didn't include selecting a folder, so I had to do it this way. If you use "Custom" and select any _file_ in the folder, the script will use the _folder_. Or you can type the path in the box next to the "Custom:" box.

Again, the problem is not with the script. The problem is with your x264.exe.

**Comment by Aegisub2019** [comment]
Hi guy, it has a new error, can you know what happed?
I have change the x264-32-8.exe

![79787位图图像](https://user-images.githubusercontent.com/55534428/65371688-02294e80-dc1b-11e9-98aa-d59bf20b4cfb.png)

**Comment by unanimated** [comment]
> failed to load avisynth
Looks like you don't have avisynth installed...

> And i have another problem, how to select the mkvmerge.exe ?write the path in the box?
Yes.

**Comment by Aegisub2019** [comment]
Thanks for your reply, but i have install the avisynth.
How i need to use it?

![图像](https://user-images.githubusercontent.com/55534428/65387036-a84a8680-dcf7-11e9-9dae-71d3f5b96032.png)
![a像](https://user-images.githubusercontent.com/55534428/65387033-a254a580-dcf7-11e9-9d33-064a3bcc17ca.png)

**Comment by unanimated** [comment]
OK, that looks correct. My installation looks the same, and I didn't do anything else with it, so I don't know why it's not loading. Again, you'd have to ask somebody who knows more about encoding. This is not exactly my area of expertise.

**Comment by Aegisub2019** [comment]
Another.
I open the Aegisub, and load the video and subtitle.
I click the script encode hardsub, it said no video detected?

![新建位图图像](https://user-images.githubusercontent.com/55534428/65387331-31af8800-dcfb-11e9-8e26-48553e3d95a4.png)

**Comment by unanimated** [comment]
You should probably make sure avisynth.dll is in windows/system32 and/or windows/SysWOW64.

You can check some pages about avisynth not working, like http://www.dlldownloader.com/avisynth-dll/

You can also try reinstalling it.

**Comment by unanimated** [comment]
"I click the script encode hardsub, it said no video detected?"
Probably because you didn't save the script (.ass) after loading the video.

**Comment by Aegisub2019** [comment]
Thank you very much, although I still can't use this script.
I have used another solution, the ffmpeg Command to hardsub.
